/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2018-11-19 at 02:19:23 UTC 
 * Modify at your own risk.
 */

package com.example.echo.facade.model;

/**
 * Model definition for ColorSpace.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the facade. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ColorSpace extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("cs_sRGB")
  private java.lang.Boolean csSRGB;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numComponents;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer type;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCsSRGB() {
    return csSRGB;
  }

  /**
   * @param csSRGB csSRGB or {@code null} for none
   */
  public ColorSpace setCsSRGB(java.lang.Boolean csSRGB) {
    this.csSRGB = csSRGB;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumComponents() {
    return numComponents;
  }

  /**
   * @param numComponents numComponents or {@code null} for none
   */
  public ColorSpace setNumComponents(java.lang.Integer numComponents) {
    this.numComponents = numComponents;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public ColorSpace setType(java.lang.Integer type) {
    this.type = type;
    return this;
  }

  @Override
  public ColorSpace set(String fieldName, Object value) {
    return (ColorSpace) super.set(fieldName, value);
  }

  @Override
  public ColorSpace clone() {
    return (ColorSpace) super.clone();
  }

}
