/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2018-11-19 at 02:19:23 UTC 
 * Modify at your own risk.
 */

package com.example.echo.facade.model;

/**
 * Model definition for Ruta.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the facade. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ruta extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Calle> calles;

  static {
    // hack to force ProGuard to consider Calle used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Calle.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String correoConductor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime hora;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String identificacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numeroPuestos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String placaCarro;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float precio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String puntoDestino;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String puntoSalida;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Calle> getCalles() {
    return calles;
  }

  /**
   * @param calles calles or {@code null} for none
   */
  public Ruta setCalles(java.util.List<Calle> calles) {
    this.calles = calles;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCorreoConductor() {
    return correoConductor;
  }

  /**
   * @param correoConductor correoConductor or {@code null} for none
   */
  public Ruta setCorreoConductor(java.lang.String correoConductor) {
    this.correoConductor = correoConductor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Ruta setFecha(com.google.api.client.util.DateTime fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getHora() {
    return hora;
  }

  /**
   * @param hora hora or {@code null} for none
   */
  public Ruta setHora(com.google.api.client.util.DateTime hora) {
    this.hora = hora;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdentificacion() {
    return identificacion;
  }

  /**
   * @param identificacion identificacion or {@code null} for none
   */
  public Ruta setIdentificacion(java.lang.String identificacion) {
    this.identificacion = identificacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumeroPuestos() {
    return numeroPuestos;
  }

  /**
   * @param numeroPuestos numeroPuestos or {@code null} for none
   */
  public Ruta setNumeroPuestos(java.lang.Integer numeroPuestos) {
    this.numeroPuestos = numeroPuestos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPlacaCarro() {
    return placaCarro;
  }

  /**
   * @param placaCarro placaCarro or {@code null} for none
   */
  public Ruta setPlacaCarro(java.lang.String placaCarro) {
    this.placaCarro = placaCarro;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPrecio() {
    return precio;
  }

  /**
   * @param precio precio or {@code null} for none
   */
  public Ruta setPrecio(java.lang.Float precio) {
    this.precio = precio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPuntoDestino() {
    return puntoDestino;
  }

  /**
   * @param puntoDestino puntoDestino or {@code null} for none
   */
  public Ruta setPuntoDestino(java.lang.String puntoDestino) {
    this.puntoDestino = puntoDestino;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPuntoSalida() {
    return puntoSalida;
  }

  /**
   * @param puntoSalida puntoSalida or {@code null} for none
   */
  public Ruta setPuntoSalida(java.lang.String puntoSalida) {
    this.puntoSalida = puntoSalida;
    return this;
  }

  @Override
  public Ruta set(String fieldName, Object value) {
    return (Ruta) super.set(fieldName, value);
  }

  @Override
  public Ruta clone() {
    return (Ruta) super.clone();
  }

}
