/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2018-11-19 at 02:19:23 UTC 
 * Modify at your own risk.
 */

package com.example.echo.facade;

/**
 * Service definition for Facade (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FacadeRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Facade extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.25.0 of the facade library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://proyectsoftwareii.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "facade/v1/";

  /**
   * The default encoded batch path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.23
   */
  public static final String DEFAULT_BATCH_PATH = "batch";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Facade(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Facade(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "actualizarRuta".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link ActualizarRuta#execute()} method to invoke the remote operation.
   *
   * @param correoConductor
   * @param horaBuscada
   * @param fechaBuscada
   * @param numeroPuestos
   * @param placaCarro
   * @param nuevaHora
   * @param nuevoPrecio
   * @return the request
   */
  public ActualizarRuta actualizarRuta(java.lang.String correoConductor, com.google.api.client.util.DateTime horaBuscada, com.google.api.client.util.DateTime fechaBuscada, java.lang.Integer numeroPuestos, java.lang.String placaCarro, com.google.api.client.util.DateTime nuevaHora, java.lang.Float nuevoPrecio) throws java.io.IOException {
    ActualizarRuta result = new ActualizarRuta(correoConductor, horaBuscada, fechaBuscada, numeroPuestos, placaCarro, nuevaHora, nuevoPrecio);
    initialize(result);
    return result;
  }

  public class ActualizarRuta extends FacadeRequest<Void> {

    private static final String REST_PATH = "actualizarRuta/{correoConductor}/{horaBuscada}/{fechaBuscada}/{numeroPuestos}/{placaCarro}/{nuevaHora}/{nuevoPrecio}";

    /**
     * Create a request for the method "actualizarRuta".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link ActualizarRuta#execute()} method to invoke the remote operation.
     * <p> {@link ActualizarRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param correoConductor
     * @param horaBuscada
     * @param fechaBuscada
     * @param numeroPuestos
     * @param placaCarro
     * @param nuevaHora
     * @param nuevoPrecio
     * @since 1.13
     */
    protected ActualizarRuta(java.lang.String correoConductor, com.google.api.client.util.DateTime horaBuscada, com.google.api.client.util.DateTime fechaBuscada, java.lang.Integer numeroPuestos, java.lang.String placaCarro, com.google.api.client.util.DateTime nuevaHora, java.lang.Float nuevoPrecio) {
      super(Facade.this, "POST", REST_PATH, null, Void.class);
      this.correoConductor = com.google.api.client.util.Preconditions.checkNotNull(correoConductor, "Required parameter correoConductor must be specified.");
      this.horaBuscada = com.google.api.client.util.Preconditions.checkNotNull(horaBuscada, "Required parameter horaBuscada must be specified.");
      this.fechaBuscada = com.google.api.client.util.Preconditions.checkNotNull(fechaBuscada, "Required parameter fechaBuscada must be specified.");
      this.numeroPuestos = com.google.api.client.util.Preconditions.checkNotNull(numeroPuestos, "Required parameter numeroPuestos must be specified.");
      this.placaCarro = com.google.api.client.util.Preconditions.checkNotNull(placaCarro, "Required parameter placaCarro must be specified.");
      this.nuevaHora = com.google.api.client.util.Preconditions.checkNotNull(nuevaHora, "Required parameter nuevaHora must be specified.");
      this.nuevoPrecio = com.google.api.client.util.Preconditions.checkNotNull(nuevoPrecio, "Required parameter nuevoPrecio must be specified.");
    }

    @Override
    public ActualizarRuta setAlt(java.lang.String alt) {
      return (ActualizarRuta) super.setAlt(alt);
    }

    @Override
    public ActualizarRuta setFields(java.lang.String fields) {
      return (ActualizarRuta) super.setFields(fields);
    }

    @Override
    public ActualizarRuta setKey(java.lang.String key) {
      return (ActualizarRuta) super.setKey(key);
    }

    @Override
    public ActualizarRuta setOauthToken(java.lang.String oauthToken) {
      return (ActualizarRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public ActualizarRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ActualizarRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ActualizarRuta setQuotaUser(java.lang.String quotaUser) {
      return (ActualizarRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ActualizarRuta setUserIp(java.lang.String userIp) {
      return (ActualizarRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String correoConductor;

    /**

     */
    public java.lang.String getCorreoConductor() {
      return correoConductor;
    }

    public ActualizarRuta setCorreoConductor(java.lang.String correoConductor) {
      this.correoConductor = correoConductor;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime horaBuscada;

    /**

     */
    public com.google.api.client.util.DateTime getHoraBuscada() {
      return horaBuscada;
    }

    public ActualizarRuta setHoraBuscada(com.google.api.client.util.DateTime horaBuscada) {
      this.horaBuscada = horaBuscada;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime fechaBuscada;

    /**

     */
    public com.google.api.client.util.DateTime getFechaBuscada() {
      return fechaBuscada;
    }

    public ActualizarRuta setFechaBuscada(com.google.api.client.util.DateTime fechaBuscada) {
      this.fechaBuscada = fechaBuscada;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer numeroPuestos;

    /**

     */
    public java.lang.Integer getNumeroPuestos() {
      return numeroPuestos;
    }

    public ActualizarRuta setNumeroPuestos(java.lang.Integer numeroPuestos) {
      this.numeroPuestos = numeroPuestos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String placaCarro;

    /**

     */
    public java.lang.String getPlacaCarro() {
      return placaCarro;
    }

    public ActualizarRuta setPlacaCarro(java.lang.String placaCarro) {
      this.placaCarro = placaCarro;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime nuevaHora;

    /**

     */
    public com.google.api.client.util.DateTime getNuevaHora() {
      return nuevaHora;
    }

    public ActualizarRuta setNuevaHora(com.google.api.client.util.DateTime nuevaHora) {
      this.nuevaHora = nuevaHora;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float nuevoPrecio;

    /**

     */
    public java.lang.Float getNuevoPrecio() {
      return nuevoPrecio;
    }

    public ActualizarRuta setNuevoPrecio(java.lang.Float nuevoPrecio) {
      this.nuevoPrecio = nuevoPrecio;
      return this;
    }

    @Override
    public ActualizarRuta set(String parameterName, Object value) {
      return (ActualizarRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "eliminarRuta".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link EliminarRuta#execute()} method to invoke the remote operation.
   *
   * @param correoConductor
   * @param hora
   * @param fecha
   * @return the request
   */
  public EliminarRuta eliminarRuta(java.lang.String correoConductor, com.google.api.client.util.DateTime hora, com.google.api.client.util.DateTime fecha) throws java.io.IOException {
    EliminarRuta result = new EliminarRuta(correoConductor, hora, fecha);
    initialize(result);
    return result;
  }

  public class EliminarRuta extends FacadeRequest<Void> {

    private static final String REST_PATH = "eliminarRuta/{correoConductor}/{hora}/{fecha}";

    /**
     * Create a request for the method "eliminarRuta".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link EliminarRuta#execute()} method to invoke the remote operation. <p>
     * {@link
     * EliminarRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param correoConductor
     * @param hora
     * @param fecha
     * @since 1.13
     */
    protected EliminarRuta(java.lang.String correoConductor, com.google.api.client.util.DateTime hora, com.google.api.client.util.DateTime fecha) {
      super(Facade.this, "POST", REST_PATH, null, Void.class);
      this.correoConductor = com.google.api.client.util.Preconditions.checkNotNull(correoConductor, "Required parameter correoConductor must be specified.");
      this.hora = com.google.api.client.util.Preconditions.checkNotNull(hora, "Required parameter hora must be specified.");
      this.fecha = com.google.api.client.util.Preconditions.checkNotNull(fecha, "Required parameter fecha must be specified.");
    }

    @Override
    public EliminarRuta setAlt(java.lang.String alt) {
      return (EliminarRuta) super.setAlt(alt);
    }

    @Override
    public EliminarRuta setFields(java.lang.String fields) {
      return (EliminarRuta) super.setFields(fields);
    }

    @Override
    public EliminarRuta setKey(java.lang.String key) {
      return (EliminarRuta) super.setKey(key);
    }

    @Override
    public EliminarRuta setOauthToken(java.lang.String oauthToken) {
      return (EliminarRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public EliminarRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EliminarRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EliminarRuta setQuotaUser(java.lang.String quotaUser) {
      return (EliminarRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public EliminarRuta setUserIp(java.lang.String userIp) {
      return (EliminarRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String correoConductor;

    /**

     */
    public java.lang.String getCorreoConductor() {
      return correoConductor;
    }

    public EliminarRuta setCorreoConductor(java.lang.String correoConductor) {
      this.correoConductor = correoConductor;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime hora;

    /**

     */
    public com.google.api.client.util.DateTime getHora() {
      return hora;
    }

    public EliminarRuta setHora(com.google.api.client.util.DateTime hora) {
      this.hora = hora;
      return this;
    }

    @com.google.api.client.util.Key
    private com.google.api.client.util.DateTime fecha;

    /**

     */
    public com.google.api.client.util.DateTime getFecha() {
      return fecha;
    }

    public EliminarRuta setFecha(com.google.api.client.util.DateTime fecha) {
      this.fecha = fecha;
      return this;
    }

    @Override
    public EliminarRuta set(String parameterName, Object value) {
      return (EliminarRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "guardarSesion".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link GuardarSesion#execute()} method to invoke the remote operation.
   *
   * @param sesion
   * @param correoConductor
   * @return the request
   */
  public GuardarSesion guardarSesion(java.lang.Integer sesion, java.lang.String correoConductor) throws java.io.IOException {
    GuardarSesion result = new GuardarSesion(sesion, correoConductor);
    initialize(result);
    return result;
  }

  public class GuardarSesion extends FacadeRequest<Void> {

    private static final String REST_PATH = "guardarSesion/{sesion}/{correoConductor}";

    /**
     * Create a request for the method "guardarSesion".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link GuardarSesion#execute()} method to invoke the remote operation. <p>
     * {@link GuardarSesion#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param sesion
     * @param correoConductor
     * @since 1.13
     */
    protected GuardarSesion(java.lang.Integer sesion, java.lang.String correoConductor) {
      super(Facade.this, "POST", REST_PATH, null, Void.class);
      this.sesion = com.google.api.client.util.Preconditions.checkNotNull(sesion, "Required parameter sesion must be specified.");
      this.correoConductor = com.google.api.client.util.Preconditions.checkNotNull(correoConductor, "Required parameter correoConductor must be specified.");
    }

    @Override
    public GuardarSesion setAlt(java.lang.String alt) {
      return (GuardarSesion) super.setAlt(alt);
    }

    @Override
    public GuardarSesion setFields(java.lang.String fields) {
      return (GuardarSesion) super.setFields(fields);
    }

    @Override
    public GuardarSesion setKey(java.lang.String key) {
      return (GuardarSesion) super.setKey(key);
    }

    @Override
    public GuardarSesion setOauthToken(java.lang.String oauthToken) {
      return (GuardarSesion) super.setOauthToken(oauthToken);
    }

    @Override
    public GuardarSesion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GuardarSesion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GuardarSesion setQuotaUser(java.lang.String quotaUser) {
      return (GuardarSesion) super.setQuotaUser(quotaUser);
    }

    @Override
    public GuardarSesion setUserIp(java.lang.String userIp) {
      return (GuardarSesion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer sesion;

    /**

     */
    public java.lang.Integer getSesion() {
      return sesion;
    }

    public GuardarSesion setSesion(java.lang.Integer sesion) {
      this.sesion = sesion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String correoConductor;

    /**

     */
    public java.lang.String getCorreoConductor() {
      return correoConductor;
    }

    public GuardarSesion setCorreoConductor(java.lang.String correoConductor) {
      this.correoConductor = correoConductor;
      return this;
    }

    @Override
    public GuardarSesion set(String parameterName, Object value) {
      return (GuardarSesion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listarRutas".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link ListarRutas#execute()} method to invoke the remote operation.
   *
   * @param correoConductor
   * @return the request
   */
  public ListarRutas listarRutas(java.lang.String correoConductor) throws java.io.IOException {
    ListarRutas result = new ListarRutas(correoConductor);
    initialize(result);
    return result;
  }

  public class ListarRutas extends FacadeRequest<com.example.echo.facade.model.RutaCollection> {

    private static final String REST_PATH = "ruta/{correoConductor}";

    /**
     * Create a request for the method "listarRutas".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link ListarRutas#execute()} method to invoke the remote operation. <p>
     * {@link
     * ListarRutas#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param correoConductor
     * @since 1.13
     */
    protected ListarRutas(java.lang.String correoConductor) {
      super(Facade.this, "GET", REST_PATH, null, com.example.echo.facade.model.RutaCollection.class);
      this.correoConductor = com.google.api.client.util.Preconditions.checkNotNull(correoConductor, "Required parameter correoConductor must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListarRutas setAlt(java.lang.String alt) {
      return (ListarRutas) super.setAlt(alt);
    }

    @Override
    public ListarRutas setFields(java.lang.String fields) {
      return (ListarRutas) super.setFields(fields);
    }

    @Override
    public ListarRutas setKey(java.lang.String key) {
      return (ListarRutas) super.setKey(key);
    }

    @Override
    public ListarRutas setOauthToken(java.lang.String oauthToken) {
      return (ListarRutas) super.setOauthToken(oauthToken);
    }

    @Override
    public ListarRutas setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListarRutas) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListarRutas setQuotaUser(java.lang.String quotaUser) {
      return (ListarRutas) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListarRutas setUserIp(java.lang.String userIp) {
      return (ListarRutas) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String correoConductor;

    /**

     */
    public java.lang.String getCorreoConductor() {
      return correoConductor;
    }

    public ListarRutas setCorreoConductor(java.lang.String correoConductor) {
      this.correoConductor = correoConductor;
      return this;
    }

    @Override
    public ListarRutas set(String parameterName, Object value) {
      return (ListarRutas) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registrarRuta".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link RegistrarRuta#execute()} method to invoke the remote operation.
   *
   * @param numeroPuestos
   * @param placaCarro
   * @param puntoSalida
   * @param puntoDestino
   * @param identificacion
   * @param hora
   * @param fecha
   * @param precio
   * @return the request
   */
  public RegistrarRuta registrarRuta(java.lang.Integer numeroPuestos, java.lang.String placaCarro, java.lang.String puntoSalida, java.lang.String puntoDestino, java.lang.String identificacion, java.lang.String hora, java.lang.String fecha, java.lang.Float precio) throws java.io.IOException {
    RegistrarRuta result = new RegistrarRuta(numeroPuestos, placaCarro, puntoSalida, puntoDestino, identificacion, hora, fecha, precio);
    initialize(result);
    return result;
  }

  public class RegistrarRuta extends FacadeRequest<Void> {

    private static final String REST_PATH = "registrarRuta/{numeroPuestos}/{placaCarro}/{puntoSalida}/{puntoDestino}/{Identificacion}/{hora}/{fecha}/{precio}";

    /**
     * Create a request for the method "registrarRuta".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link RegistrarRuta#execute()} method to invoke the remote operation. <p>
     * {@link RegistrarRuta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param numeroPuestos
     * @param placaCarro
     * @param puntoSalida
     * @param puntoDestino
     * @param identificacion
     * @param hora
     * @param fecha
     * @param precio
     * @since 1.13
     */
    protected RegistrarRuta(java.lang.Integer numeroPuestos, java.lang.String placaCarro, java.lang.String puntoSalida, java.lang.String puntoDestino, java.lang.String identificacion, java.lang.String hora, java.lang.String fecha, java.lang.Float precio) {
      super(Facade.this, "POST", REST_PATH, null, Void.class);
      this.numeroPuestos = com.google.api.client.util.Preconditions.checkNotNull(numeroPuestos, "Required parameter numeroPuestos must be specified.");
      this.placaCarro = com.google.api.client.util.Preconditions.checkNotNull(placaCarro, "Required parameter placaCarro must be specified.");
      this.puntoSalida = com.google.api.client.util.Preconditions.checkNotNull(puntoSalida, "Required parameter puntoSalida must be specified.");
      this.puntoDestino = com.google.api.client.util.Preconditions.checkNotNull(puntoDestino, "Required parameter puntoDestino must be specified.");
      this.identificacion = com.google.api.client.util.Preconditions.checkNotNull(identificacion, "Required parameter identificacion must be specified.");
      this.hora = com.google.api.client.util.Preconditions.checkNotNull(hora, "Required parameter hora must be specified.");
      this.fecha = com.google.api.client.util.Preconditions.checkNotNull(fecha, "Required parameter fecha must be specified.");
      this.precio = com.google.api.client.util.Preconditions.checkNotNull(precio, "Required parameter precio must be specified.");
    }

    @Override
    public RegistrarRuta setAlt(java.lang.String alt) {
      return (RegistrarRuta) super.setAlt(alt);
    }

    @Override
    public RegistrarRuta setFields(java.lang.String fields) {
      return (RegistrarRuta) super.setFields(fields);
    }

    @Override
    public RegistrarRuta setKey(java.lang.String key) {
      return (RegistrarRuta) super.setKey(key);
    }

    @Override
    public RegistrarRuta setOauthToken(java.lang.String oauthToken) {
      return (RegistrarRuta) super.setOauthToken(oauthToken);
    }

    @Override
    public RegistrarRuta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegistrarRuta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegistrarRuta setQuotaUser(java.lang.String quotaUser) {
      return (RegistrarRuta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegistrarRuta setUserIp(java.lang.String userIp) {
      return (RegistrarRuta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer numeroPuestos;

    /**

     */
    public java.lang.Integer getNumeroPuestos() {
      return numeroPuestos;
    }

    public RegistrarRuta setNumeroPuestos(java.lang.Integer numeroPuestos) {
      this.numeroPuestos = numeroPuestos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String placaCarro;

    /**

     */
    public java.lang.String getPlacaCarro() {
      return placaCarro;
    }

    public RegistrarRuta setPlacaCarro(java.lang.String placaCarro) {
      this.placaCarro = placaCarro;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String puntoSalida;

    /**

     */
    public java.lang.String getPuntoSalida() {
      return puntoSalida;
    }

    public RegistrarRuta setPuntoSalida(java.lang.String puntoSalida) {
      this.puntoSalida = puntoSalida;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String puntoDestino;

    /**

     */
    public java.lang.String getPuntoDestino() {
      return puntoDestino;
    }

    public RegistrarRuta setPuntoDestino(java.lang.String puntoDestino) {
      this.puntoDestino = puntoDestino;
      return this;
    }

    @com.google.api.client.util.Key("Identificacion")
    private java.lang.String identificacion;

    /**

     */
    public java.lang.String getIdentificacion() {
      return identificacion;
    }

    public RegistrarRuta setIdentificacion(java.lang.String identificacion) {
      this.identificacion = identificacion;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String hora;

    /**

     */
    public java.lang.String getHora() {
      return hora;
    }

    public RegistrarRuta setHora(java.lang.String hora) {
      this.hora = hora;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String fecha;

    /**

     */
    public java.lang.String getFecha() {
      return fecha;
    }

    public RegistrarRuta setFecha(java.lang.String fecha) {
      this.fecha = fecha;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float precio;

    /**

     */
    public java.lang.Float getPrecio() {
      return precio;
    }

    public RegistrarRuta setPrecio(java.lang.Float precio) {
      this.precio = precio;
      return this;
    }

    @Override
    public RegistrarRuta set(String parameterName, Object value) {
      return (RegistrarRuta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "verificarSesion".
   *
   * This request holds the parameters needed by the facade server.  After setting any optional
   * parameters, call the {@link VerificarSesion#execute()} method to invoke the remote operation.
   *
   * @param correoConductor
   * @return the request
   */
  public VerificarSesion verificarSesion(java.lang.String correoConductor) throws java.io.IOException {
    VerificarSesion result = new VerificarSesion(correoConductor);
    initialize(result);
    return result;
  }

  public class VerificarSesion extends FacadeRequest<com.example.echo.facade.model.Devolver> {

    private static final String REST_PATH = "verificarSesion/{correoConductor}";

    /**
     * Create a request for the method "verificarSesion".
     *
     * This request holds the parameters needed by the the facade server.  After setting any optional
     * parameters, call the {@link VerificarSesion#execute()} method to invoke the remote operation.
     * <p> {@link VerificarSesion#initialize(com.google.api.client.googleapis.services.AbstractGoogleC
     * lientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param correoConductor
     * @since 1.13
     */
    protected VerificarSesion(java.lang.String correoConductor) {
      super(Facade.this, "POST", REST_PATH, null, com.example.echo.facade.model.Devolver.class);
      this.correoConductor = com.google.api.client.util.Preconditions.checkNotNull(correoConductor, "Required parameter correoConductor must be specified.");
    }

    @Override
    public VerificarSesion setAlt(java.lang.String alt) {
      return (VerificarSesion) super.setAlt(alt);
    }

    @Override
    public VerificarSesion setFields(java.lang.String fields) {
      return (VerificarSesion) super.setFields(fields);
    }

    @Override
    public VerificarSesion setKey(java.lang.String key) {
      return (VerificarSesion) super.setKey(key);
    }

    @Override
    public VerificarSesion setOauthToken(java.lang.String oauthToken) {
      return (VerificarSesion) super.setOauthToken(oauthToken);
    }

    @Override
    public VerificarSesion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (VerificarSesion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public VerificarSesion setQuotaUser(java.lang.String quotaUser) {
      return (VerificarSesion) super.setQuotaUser(quotaUser);
    }

    @Override
    public VerificarSesion setUserIp(java.lang.String userIp) {
      return (VerificarSesion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String correoConductor;

    /**

     */
    public java.lang.String getCorreoConductor() {
      return correoConductor;
    }

    public VerificarSesion setCorreoConductor(java.lang.String correoConductor) {
      this.correoConductor = correoConductor;
      return this;
    }

    @Override
    public VerificarSesion set(String parameterName, Object value) {
      return (VerificarSesion) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Facade}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
      setBatchPath(DEFAULT_BATCH_PATH);
    }

    /** Builds a new instance of {@link Facade}. */
    @Override
    public Facade build() {
      return new Facade(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FacadeRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFacadeRequestInitializer(
        FacadeRequestInitializer facadeRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(facadeRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
